### ISSUE TITLE
TuyaOpenCloudAPI.groovy - bug

### ISSUE THREAD

**Issue by drjuliankeates** [bradsjm/hubitat-drivers#4]
the temperature is scaled but the set point is not, this means the setpoint = x10 more than it should be.
value just needs to be scaled as per the first block of code

if (status.code in tuyaFunctions.temperature) {
            Map set = deviceStatusSet[status.code] ?: defaults[status.code]
            String value = scale(status.value, set.scale)
            String unit = set.unit
            if (txtEnable) { LOG.info "${dw} temperature is ${value}${unit}" }
            return [ [ name: 'temperature', value: value, unit: unit, descriptionText: "temperature is ${value}${unit}" ] ]
        }

        if (status.code in tuyaFunctions.temperatureSet) {
            Map set = deviceStatusSet[status.code] ?: defaults[status.code]
            String value = status.value
            String unit = set.unit
            if (txtEnable) { LOG.info "${dw} heating set point is ${value}${unit}" }
            return [ [ name: 'heatingSetpoint', value: value, unit: unit, descriptionText: "heating set point is ${value}${unit}" ] ]
        }

**Comment by bradsjm** [comment]
Added to the development branch, thanks!

**Comment by bradsjm** [comment]
Promoted to production branch
