### ISSUE TITLE
Tuya Cloud

### ISSUE THREAD

**Issue by apowers313** [bradsjm/hubitat-drivers#6]
Hey, I’ve been using the Tuya driver for a few weeks and it works great, thanks for writing it. :)

I just picked up a [MoesGo IR Blaster](https://www.amazon.com/gp/product/B085Y47L4X) and have it working with the Tuya app, but it doesn’t work with the Hubitat driver because it’s a remote device. Any chance you’d accept a pull request to add remote control support?

**Comment by bradsjm** [comment]
While I don't have time to write code at the moment, I am accepting pull requests!
